project1/src/epood1/model/data/Order.java
package epood1.model.data;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.GenerationType;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import epood1.model.data.CustomerAddress;
import epood1.model.data.OrderItem;

/**
 * 
 * @author Jaanus Ojasoo
 *   May 17, 2013
 */

@Entity
@Table(name = "order_")
public class Order implements Serializable {

	private static final long serialVersionUID = 2740185063L;

	@Id
	@Column(name = "order_")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="s_order")
    @SequenceGenerator(name="s_order", sequenceName="s_order", allocationSize=1)
    
	private int order;
	
	@Column(name = "order_status_type")
	private int orderStatusType;
	
	@Column(name = "customer")
	private int customer;
	
	@Column(name = "order_number")
	private String orderNumber;
	
	@Column(name = "created")
	private Date created;
	
	@Column(name = "updated")
	private Date updated;
	
	@Column(name = "customer_confirmed")
	private Date customerConfirmed;
	
	@Column(name = "note")
	private String note;
	
	@Column(name = "order_type")
	private int orderType;
	
	@Column(name = "shipping_address")
	private int shippingAddressId;
	
	@ManyToOne
	@JoinColumn(name = "shipping_address", referencedColumnName = "cst_address", insertable = false, updatable = false)
	private CustomerAddress shippingAddress;
	
	@OneToMany
	@JoinColumn(name = "order_")
	@Cascade(CascadeType.SAVE_UPDATE)
	private List<OrderItem> orderItems = new ArrayList<OrderItem>();
	
	/**
	 * @return the order
	 */
	public int getOrder() {
		return order;
	}
	/**
	 * @param order the order to set
	 */
	public void setOrder(int order) {
		this.order = order;
	}
	/**
	 * @return the orderStatusType
	 */
	public int getOrderStatusType() {
		return orderStatusType;
	}
	/**
	 * @param orderStatusType the orderStatusType to set
	 */
	public void setOrderStatusType(int orderStatusType) {
		this.orderStatusType = orderStatusType;
	}
	/**
	 * @return the customer
	 */
	public int getCustomer() {
		return customer;
	}
	/**
	 * @param customer the customer to set
	 */
	public void setCustomer(int customer) {
		this.customer = customer;
	}
	/**
	 * @return the orderNumber
	 */
	public String getOrderNumber() {
		return orderNumber;
	}
	/**
	 * @param umber the orderNumber to set
	 */
	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}
	/**
	 * @return the created
	 */
	public Date getCreated() {
		return created;
	}
	/**
	 * @param created date
	 */
	public void setCreated(Date created) {
		this.created = created;
	}
	/**
	 * @return the updated
	 */
	public Date getUpdated() {
		return updated;
	}
	/**
	 * @param updated the updated to set
	 */
	public void setUpdated(Date updated) {
		this.updated = updated;
	}
	/**
	 * @return the customerConfirmed
	 */
	public String getCustomerConfirmed() {
		return new SimpleDateFormat("dd-MM-yyyy").format(customerConfirmed);
	}

	public Date getCustomerConfirmedDate() {
		return customerConfirmed;
	}
	/**
	 * @param customerConfirmed the customerConfirmed to set
	 */
	public void setCustomerConfirmed(Date customerConfirmed) {
		this.customerConfirmed = customerConfirmed;
	}
	/**
	 * @return the note
	 */
	public String getNote() {
		return note;
	}
	/**
	 * @param note the note to set
	 */
	public void setNote(String note) {
		this.note = note;
	}
	/**
	 * @return the orderType
	 */
	public int getOrderType() {
		return orderType;
	}
	/**
	 * @param orderType the orderType to set
	 */
	public void setOrderType(int orderType) {
		this.orderType = orderType;
	}
	/**
	 * @return the shippingAddressId
	 */
	public int getShippingAddressId() {
		return shippingAddressId;
	}
	/**
	 * @param shippingAddressId the shippingAddressId to set
	 */
	public void setShippingAddressId(int shippingAddressId) {
		this.shippingAddressId = shippingAddressId;
	}
	
	public List<OrderItem> getOrderItems() {
	    return orderItems;
	}
	
	public OrderItem getOrderItem(int productId) {
	    for (OrderItem orderItem : orderItems) {
	      if (orderItem.getProductId() == productId) {
	        return orderItem;
	      }
	    }
	    return null;
	}
	
	public boolean containsItem(int productId) {
	    for (final OrderItem orderItem : orderItems) {
	      if (orderItem.getProductId() == productId) {
	        return true;
	      }
	    }
	    return false;
	  }

	  public void removeItem(int productId) {
	    // Evading ConcurrentModificationException
	    List<OrderItem> itemsToRemove = new ArrayList<OrderItem>();
	    for (OrderItem orderItem : orderItems) {
	      if (orderItem.getProductId() == productId) {
	        itemsToRemove.add(orderItem);
	      }
	    }
	    orderItems.removeAll(itemsToRemove);
	  }

	  public double getOrderTotalPrice() {
	    double totalPrice = 0;
	    for (final OrderItem oi : orderItems) {
	   //   totalPrice += oi.getProduct().getPrice() * oi.getItemCount();  //hind toote originaalhinnaga
	    	totalPrice += oi.getItemCount() * oi.getItemPrice();
	    }
	    return totalPrice;
	  }
	  
	  
	  public double getRowTotalPrice(int productId) {
		    double totalPrice = 0;
		    for (final OrderItem oi : orderItems) {
		    	if (oi.getProductId() == productId) {
		    		totalPrice += oi.getItemCount() * oi.getItemPrice();
		    	}	
		    }
		    return totalPrice;
		  }
	
	  public int getAle(int productId) {
		  int ale = 0;
		  for (final OrderItem orderItem : orderItems) {
			  if (orderItem.getProductId() == productId) {	
				  ale = (int) ((1-(orderItem.getItemPrice() / orderItem.getProduct().getPrice() )) * 100);
			  }	  
		  }
		  return ale;
	  }
	  
		  
	/**
	 * @param shippingAddress the shippingAddress to set
	 */
	public void setShippingAddress(CustomerAddress shippingAddress) {
		this.shippingAddress = shippingAddress;
	}
	/**
	 * @return the shippingAddress
	 */
	public CustomerAddress getShippingAddress() {
		return shippingAddress;
	}
	
	@Override
	  public String toString() {
	    return "Order[" + orderItems + "]";
	}
	
}

project1/src/epood1/model/data/OrderItem.java
package epood1.model.data;

import java.io.Serializable;
import java.text.DecimalFormat;
import java.text.NumberFormat;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import epood1.model.data.Product;

/**
 * 
 * @author Jaanus Ojasoo
 *   May 17, 2013
 */


@Entity
@Table(name = "order_item")
public class OrderItem implements Serializable {

	private static final long serialVersionUID = 3325120894174470680L;
	private final static NumberFormat NF = new DecimalFormat("0.0###");
	
	@Id
	@Column(name = "order_item")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="s_order_item")
    @SequenceGenerator(name="s_order_item", sequenceName="s_order_item", allocationSize=1)
	private int orderItem;
	
	@Column(name = "order_")
	private int order;
	
	@Column(name = "product")
	private int productId;
	
	@Column(name = "item_count")
	private int itemCount;
	
	@Column(name = "item_price")
	private double itemPrice;
	
	@ManyToOne
	@JoinColumn(name = "product", insertable = false, updatable = false)
	private Product product;
	
	/**
	 * @return the orderItem
	 */
	public int getOrderItem() {
		return orderItem;
	}
	/**
	 * @param orderItem the orderItem to set
	 */
	public void setOrderItem(int orderItem) {
		this.orderItem = orderItem;
	}
	/**
	 * @return the order
	 */
	public int getOrder() {
		return order;
	}
	/**
	 * @param order the order to set
	 */
	public void setOrder(int order) {
		this.order = order;
	}
	/**
	 * @return the productId
	 */
	public int getProductId() {
		return productId;
	}
	/**
	 * @param productId the productId to set
	 */
	public void setProductId(int productId) {
		this.productId = productId;
	}
	/**
	 * @return the itemCount
	 */
	public int getItemCount() {
		return itemCount;
	}
	/**
	 * @param itemCount the itemCount to set
	 */
	public void setItemCount(int itemCount) {
		this.itemCount = itemCount;
	}
	/**
	 * @return the itemPrice
	 */
	public double getItemPrice() {
	//	DecimalFormat df = new DecimalFormat("#.##");
	//	NumberFormat formatter = new DecimalFormat("##.###");
	//	double newPrice = Math.round(itemPrice*100.00)/100.00;
	//	return Double.valueOf(df.format(itemPrice).replaceAll(",", "."));
		return itemPrice;
	}
	/**
	 * @param itemPrice 
	 */
	public void setItemPrice(double itemPrice) {
		this.itemPrice = itemPrice;
	}
	/**
	 * @param product the product to set
	 */
	public void setProduct(Product product) {
		this.product = product;
	}
	/**
	 * @return the product
	 */
	public Product getProduct() {
		return product;
	}

	
}

project1/src/epood1/model/data/Product.java
package epood1.model.data;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 
 * @author Jaanus Ojasoo
 *   May 20, 2013
 */

@Entity
@Table(name="product")
public class Product implements Serializable {

	private static final long serialVersionUID = -7325281561911437634L;
	
	@Id
	@Column(name = "product")
	private int productId;
	
	@Column(name = "code")
	private String code;
	
	@Column(name = "name")
	private String name;
	
	@Column(name = "description")
	private String description;
	
	@Column(name = "created")
	private Date created;
	
	@Column(name = "updated")
	private Date updated;
	
	@Column(name = "price")
	private double price;
	
	@Column(name = "producer")
	private String producer;
	
	@Column(name = "catalog")
	private String product_catalog;
	
	/**
	 * @return the productId
	 */
	public int getProductId() {
		return productId;
	}

	/**
	 * @param productId the productId to set
	 */
	public void setProductId(int productId) {
		this.productId = productId;
	}

	/**
	 * @return the code
	 */
	public String getCode() {
		return code;
	}

	/**
	 * @param code the code to set
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the created
	 */
	public Date getCreated() {
		return created;
	}

	/**
	 * @param created the created to set
	 */
	public void setCreated(Date created) {
		this.created = created;
	}

	/**
	 * @return the updated
	 */
	public Date getUpdated() {
		return updated;
	}

	/**
	 * @param updated the updated to set
	 */
	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	/**
	 * @return the price
	 */
	public double getPrice() {
		return price;
	}

	/**
	 * @param price the price to set
	 */
	public void setPrice(double price) {
		this.price = price;
	}

	/**
	 * @return the producer
	 */
	public String getProducer() {
		return producer;
	}

	/**
	 * @param producer the producer to set
	 */
	public void setProducer(String producer) {
		this.producer = producer;
	}

	/**
	 * @param product_catalog the product_catalog to set
	 */
	public void setProduct_catalog(String product_catalog) {
		this.product_catalog = product_catalog;
	}

	/**
	 * @return the product_catalog
	 */
	public String getProduct_catalog() {
		return product_catalog;
	}

	
}

project1/WebContent/jsp/cartItems.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ page import="epood1.model.data.CustomerAddress"  %>
<%@ page import="epood1.model.data.OrderItem"  %> 
<%@ page import="epood1.model.data.Order"  %>
<%@ page import="epood1.model.DAO.CustomerDAO"  %>
<%@ page import="java.util.List"  %> 
<jsp:include page="/jsp/header.jsp" />

<script src="js/remove.js" type="text/javascript"></script>
<%
	Order Order = null;
	Double total = 0.00;
if (session.getAttribute("current_order")!=null)
	Order = (Order) session.getAttribute("current_order");
if (Order == null || Order.getOrderItems().size() == 0) {
	out.println("Your cart is empty.");
} else {
%>
<div>
  <form action="c?mode=cart&clearAll=all" method="post">
    <input type="submit" value="Empty Cart">
  </form>
</div>
<br>

<table class="products">
  <tr>
    <th>Product name</th>
    <th>Quantity</th>
    <th>Price</th>
    <th>Row-total</th>
    <th></th>
  </tr>
  <%
  	for (OrderItem item : Order.getOrderItems()) {
  %>
  	<tr>
      <td><a href='c?mode=product&productId=<%=item.getProduct().getProductId() %>'>
      <%=item.getProduct().getName()%></a>
      </td>
      <td>
        <form action="c?mode=cart" method="post">
          <input name="itemCount" type="text" size="2" maxlength="2" value="<%= item.getItemCount() %>" /> 
          <input name="productId" type="hidden" value="<%= item.getProduct().getProductId() %>" />
          <input type="submit" value="Update" />
        </form>
      </td>
      <td> <%=item.getProduct().getPrice()%>  </td>
      <td> <%=(item.getProduct().getPrice() * item.getItemCount())%>  </td>
       <td>
      	<img src="images/remove.gif" Alt="remove"  onclick="removeItem(<%= item.getProduct().getProductId() %>);" />
      </td>
      
      </tr>
  <%
  	total += item.getProduct().getPrice() * item.getItemCount();
    }
  %>
</table>
<div align="right">  <br/> Total: <b><%=total%></b></div>
<div>
  
  <form action="c?mode=cart&submit=1" method="post">
  Notes:<br>
   <textarea rows="3" cols="25" name="note"></textarea>
   <br>
  <br/>Please select the shipping address: <br/>
    <select name="customerAddressId">
      <%
      	List<CustomerAddress> customerAddr = new CustomerDAO().getCustomerAddresses( (Integer) session.getAttribute("user"));
            for (CustomerAddress address : customerAddr) {
      %>
      		<option value="<%= address.getCustomerAddress() %>"><%= address.getAddress() %></option>
      <%} %>
    </select> 
    
    </br>
    <input type="submit" value="Confirm order">
  </form>
</div>
<%} %>

<jsp:include page="/jsp/footer.jsp" />

project1/WebContent/jsp/footer.jsp
<%@ page import="epood1.model.data.Order"  %>


	</td>
    </tr>
    <tr><td colspan="2" align="right"><font  color="#CCC"> 2013&copy;</font> </td></tr>
  </tbody>
</table>
</html>

project1/WebContent/jsp/header.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ page import="epood1.model.data.Product"  %> 
<%@ page import="epood1.model.data.ProductCatalog"  %> 
<%@ page import="epood1.model.DAO.ProductDAO"  %>
<%@ page import="epood1.model.DAO.ProductCatalogDAO"%>
<%@ page import="java.util.List"  %> 
<%@ page import="epood1.model.data.Order"  %>
<jsp:useBean id="ProductCatalogDAO" scope="page" class="epood1.model.DAO.ProductCatalogDAO" />
<jsp:useBean id="specialCatalog" scope="request" class="epood1.model.data.ProductCatalog" />

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<link type="text/css" rel="stylesheet" href="css/style.css" />
<title>IDU0200 EPOOD1</title>
<body>
<table align="center" width="959px">
  <tr>
    
    <% if(session.getAttribute( "user" ) != null){ %>
	<td align="left">
	<table width="959px">
		<tr>
			<td align="Left">
	         <span class="menu"> Welcome: <b><%  out.println(session.getAttribute("username"));%></b> | 
              <a href="c?mode=ordersearch">Order history</a> | 
              <a href="c?mode=cart">
					<img align="bottom" src="images/shopping_cart.png" Alt="Cart"> ( <%
                 if (session.getAttribute("current_order") == null)
        		   out.println("0");
        	   else
        	   	   out.println(((Order) session.getAttribute("current_order")).getOrderItems().size()); %>)</a> | 
              <a href="c?mode=logout">Logoff</a>
              </span>
            </td> 
          <!--  search -->  
          <!-- c?mode=product&search=1&criteria=toode&productCategoryId=&created=&updated=&priceStart=&priceEnd= -->
            <td align="right" rowspan=2>
				<form method="get" action="c">
					<input name="mode" type="hidden" value="product" />
					<input name="search" type="hidden" value="1" />
					<input name="cId" type="hidden" value=
					<%= (request.getParameter("catalogId")==null)? "0" : request.getParameter("catalogId") %> />
					<input type="text" name="criteria" />
					<input type="submit" value="Search" />
				</form>  
				<span class="menu">  
				 <a href="c?mode=product&form=1&cId=<%= (request.getParameter("catalogId")==null)? "0" : request.getParameter("catalogId") %>">
				 Advanced search</span></a>        
            </td> 
          <!-- end of search -->  
        </tr>
     </table>
    <%} else { %>
    <td align="right">
    <jsp:include page="/jsp/login.jsp" />
    <%} %>	
    
    </td>
  </tr>
  <tr>
  	<td>
  	<img src="images/epood_banner.jpg" Alt="banner">
  	</td>
  </tr>	
</table>


<table align="center" width="959px">
  <tbody>
    <tr>
	<td valign="top">
	
	<!-- Product categories -->
	<div id="rounded">
		<table class="product_catalog">
		<tr>
			<th><span class="product_head">Product Catalog:</span></th>
		</tr>
		
		<tr>
			<td>* <a href='c?mode=product'>All Products</a></td>
		</tr>
		
		<%
		List<ProductCatalog> productList = null;
		try {
	    	productList =  ProductCatalogDAO.getAllCatalogs();
	    	if (productList != null)
	     		for (ProductCatalog catalog : productList) {    
	    	 	 	out.println("<tr><td>* <a href='c?mode=product&catalogId="
	    			  +catalog.getProductCatalog()+"'>"+ catalog.getName() +"</a></tr></td>");
	     		}
	 	} catch(Exception ex) { 
	 		out.println("Error occured");
			if (productList == null) {
				out.println("Query return 0 values  " + productList);
				out.println(ex.getMessage());
			}
		}
	         
	 	%>
		 </table>
	</div>
 	<!-- end of  Product categories -->
 	</td>
 	
 	<!-- content -->
    <td width="80%" align="left" valign="top">
    
    
    

project1/WebContent/jsp/login.jsp
<form action='c?mode=catalogs' method=POST>
<table>
<tr><td>Username:</td><td><input type='text' name='username' value=''></td></tr>
<tr><td>Password:</td><td><input type='password' name='password' value=''></td></tr>
<tr><td></td><td><input type='submit' value='login'></td></tr>
</table>
</form>

project1/WebContent/jsp/orderHistory.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ page import="epood1.model.data.Order"  %>    
<%@ page import="epood1.model.DAO.OrderDAO"  %>
<%@ page import="java.util.List"  %> 

<jsp:include page="/jsp/header.jsp" />
<script src="js/orderInfo.js" type="text/javascript"></script>

<%
	List<Order> orders = new OrderDAO().getOrdersForCustomer((Integer)session.getAttribute("user"));

if (orders.size()==0) {
	out.println("You haven't order anything yet");
} else {
%>

<br/>
Your previous orders<br/><br/>
<table class="products">
	<tr>
        <th>No.</th>
        <th>Order date</th>
        <th>Order address</th>
        <th>Total</th>
    </tr>
<% for(Order customerOrder : orders) { %>
	<tr>
	<% out.println("<td><a href='javascript:select_product("+ customerOrder.getOrder()+")'>"+customerOrder.getOrder()+"</a></td>");%>
	<td><%= customerOrder.getCustomerConfirmed() %></td>
	<td><%= customerOrder.getShippingAddress().getAddress() %></td>
	<td><%= customerOrder.getOrderTotalPrice() %></td>
	</tr>
<%} %>
<%} %>
</table>
<br/>

<div ID="response" style="visibility:hidden;"></div>

<jsp:include page="/jsp/footer.jsp" />

project1/WebContent/jsp/orderItems.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ page import="epood1.model.data.OrderItem"  %>  

<jsp:useBean id="order" scope="request" class="epood1.model.data.Order" />

<table class="order_head">
  <tr>
    <td class="head">Order details:</b></td>
  </tr>
  <tr>
    <td>Order number: <b>${order.order}</b></td>
  </tr>
  <tr>
    <td>Date ordered: <b>${order.customerConfirmed}</b></td>
  </tr>
  <tr>
    <td>Order address: <b>${order.shippingAddress.address}</b></td>
  </tr>
  <tr>
    <td>Order total price: <b>${order.orderTotalPrice}</b></td>
  </tr>
</table>
<br />
<table class="order">
  <tr>
    <th>Product</th>
    <th>Quantity</th>
    <th>Orig Price</th>
    <th>YOUR prize</th>
    <th>Ale</th>
    <th>Sub-total</th>
  </tr>
	<% for (OrderItem orderItem : order.getOrderItems()) { %>
		<tr>
			<td><a href='c?mode=product&productId=<%= orderItem.getProductId() %>'>
			<%= orderItem.getProduct().getName() %></a></td>
			<td><%= orderItem.getItemCount() %></td>
			<td><%= orderItem.getProduct().getPrice() %></td>
			<td><%= orderItem.getItemPrice() %></td>
			<td><%= order.getAle(orderItem.getProductId()) %>%</td>
			<td><%= order.getRowTotalPrice(orderItem.getProductId()) %></td>
		</tr>	
	<%} %>
	<tr>
		<td colspan="6" align="right"><b>Total:</b>  <%= order.getOrderTotalPrice() %></td>
	</tr>
</table>
Note: <%= order.getNote() %>

project1/WebContent/jsp/product.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ page import="epood1.model.data.Product"  %> 
<%@ page import="java.util.List"  %> 
<jsp:useBean id="ProductDAO" scope="page" class="epood1.model.DAO.ProductDAO" />
<jsp:useBean id="product" scope="request" class="epood1.model.data.Product" />

<jsp:include page="/jsp/header.jsp" />

<table align="left" class="products">
	<tr>
		<td><h3>${product.name}</h3></td>
		<td rowspan="4"><img src="images/toode${product.productId}.png"></td>
	</tr>
	<tr>
    	<td colspan="1">${product.description} <br/><br/></td>
    </tr>
	<tr>
    	<td align="left">Price: <b>${product.price}</b> </td>
    </tr>
    <tr>	
    	<td align="right" width="50%">
		    <%if (session.getAttribute( "user" ) != null) { %>
		    <form method="post" action="c?mode=cart">
		          Quantity: 
		          <input type="hidden" name="productId" value="${product.productId}" /> 
		          <input type="text" size="4" name="itemCount" maxlength="2" value="1" style="text-align: right" /> 
		          <input type="submit" value="Add to cart" />
		    </form>
    <%} %>
    	</td>
    </tr>
	
</table>
<jsp:include page="/jsp/footer.jsp" />

project1/WebContent/jsp/products.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    
<%@ page import="java.util.List"  %>     
<%@ page import="epood1.model.data.Product"  %> 
<%@ page import="epood1.model.DAO.ProductDAO"  %> 
<jsp:useBean id="ProductCatalogDAO" scope="page" class="epood1.model.DAO.ProductCatalogDAO" />
<jsp:useBean id="catalog" scope="request" class="epood1.model.data.ProductCatalog" />

<jsp:include page="/jsp/header.jsp" />

<div class="crumps">
	<%
		List<Product> productList = null;
		if (catalog.getProducts().size() == 0){
			productList =  new ProductDAO().getAllProducts();
			out.println("Catalog: All Products");
		} else {
			productList =  catalog.getProducts();
			out.println("Catalog: "+ catalog.getName());
		}
	%>
  </div></br>
  	
  <%  try {
 		  out.println("<table align='left' class='products'>");
 		  out.println("<tr><th>Thumb</th><th>Product</th><th>Description</th><th>Price</th></tr>");
      for (Product product : productList) {    
    	  out.println("<tr>"
    			  +"<td><img src='images/toode" + product.getProductId() +"_thumb.png' alt='Pilt"+ product.getProductId() +"'></td>"
    			  +"<td><a href='c?mode=product&productId=" + product.getProductId()+"'>" + product.getName() +"</a></td>"
    			  +"<td>" + product.getDescription().substring(0,Math.min(product.getDescription().length(),30)) +"...</td>"
    			  +"<td>" + product.getPrice() +"</td>"
    			  +"</tr>");
      }
 	} catch(Exception ex) { 
		out.println("Error");
		if (productList == null) {
			out.println("No products currently available");
		}
	}
         
 	%>
 	</table>

<jsp:include page="/jsp/footer.jsp" />
